### ISSUE TITLE
SAGER CLEVO NH58HPQ touchpad fix possible firmware available?

### ISSUE THREAD

**Issue by allen-munsch** [patacca/linux-tigerlake-hack#1]
Thanks for putting this together.

Just wanted to add a note here.

- https://support.system76.com/articles/system-firmware
- https://bugzilla.kernel.org/show_bug.cgi?id=213579

So according to:

- https://github.com/pop-os/linux/issues/57

It seems like the system76 firmware has a fix for the TGL-H bug?

Just trying to track down which repo that comes from.

**Comment by allen-munsch** [comment]
wishing myself luck:

```
sudo apt-get install build-essential libgtk-3-dev libatk1.0-dev libudev-dev libglib2.0-dev libcairo-dev libpango-1.0.0-dev libpango1.0-dev libgdk-pixbuf2.0-dev liblzma-dev libdbus-1-dev
git clone git@github.com:pop-os/system76-firmware.git
cd system76-firmware/
curl https://sh.rustup.rs -sSf | sh
source ~/.cargo/env

make
sudo make install

cd ..

git clone git@github.com:pop-os/firmware-manager.git
cd firmware-manager/
make prefix=/usr
sudo make install prefix=/usr

# ensure ME mode is disabled and then?
sudo system76-firmware-cli schedule
# reboot
```

**Comment by allen-munsch** [comment]
would be interested in hearing how i could go about adding support. 

```
02:43:06 jm@jm ~ → sudo system76-firmware-cli schedule
Automatic transition: NH5_7HPQ -> NH5_7HPQ
downloading tail
opening download cache
downloading manifest.json
downloading system76-firmware-update.tar.xz
downloading Not Applicable_f4a583696d9220a2682f8734586a8ef7d0b48f691c68566f284da01556e25db9.tar.xz
downloading tail
opening download cache
downloading manifest.json
downloading system76-firmware-update.tar.xz
downloading Not Applicable_f4a583696d9220a2682f8734586a8ef7d0b48f691c68566f284da01556e25db9.tar.xz
downloading tail
opening download cache
downloading manifest.json
downloading system76-firmware-update.tar.xz
downloading Not Applicable_f4a583696d9220a2682f8734586a8ef7d0b48f691c68566f284da01556e25db9.tar.xz
downloading tail
opening download cache
downloading manifest.json
downloading system76-firmware-update.tar.xz
downloading Not Applicable_f4a583696d9220a2682f8734586a8ef7d0b48f691c68566f284da01556e25db9.tar.xz
system76-firmware: failed to download: Not Applicable_f4a583696d9220a2682f8734586a8ef7d0b48f691c68566f284da01556e25db9.tar.xz not found


02:43:31 jm@jm ~ → sudo system76-firmware-cli schedule --open
Open transition: NH5_7HPQ -> NH5_7HPQ
system76-firmware: failed to download: Model 'Not Applicable' is not supported by open firmware and EC at this time
```

- https://www.reddit.com/r/System76/comments/n15dan/how_to_update_firmware_when_using_a_non_popos/


closing this issue as it's not directly related to the changes in overriding the pin numbers

**Comment by allen-munsch** [comment]
closing this issue as it's not directly related to the changes in overriding the pin numbers

don't have the time to look further into why the system76 firmware doesn't work

just some notes for posterity

**Comment by patacca** [comment]
Thank you for the info. Unfortunately I don't know whether System76 firmware can be safely installed on other Clevo laptops. It would be nice to have a list of which clevo models are being used by System76 but I doubt they are willing to disclose that.
I already contacted Clevo to notify them of the bug but I don't think they will replly anytime soon.
We should reach someone working with clevo to get some exposure

**Comment by allen-munsch** [comment]
Also to note to anyone who finds themselves here.

I ended up building these debian packages and using those, just the compiled kernel with this repos kernel hack : https://github.com/patacca/linux-tigerlake-hack/pull/3/files
